// SPDX-License-Identifier: AGPL-3.0-or-later

// Package ghostcam embeds the legal notices so the executable is
// self-contained: GhostCam's own license and the third-party license texts
// (regenerated by scripts/gen-notices.sh) are shown in the app at /licenses.
package ghostcam

import _ "embed"

//go:embed LICENSE
var license string

//go:embed third_party_licenses.txt
var thirdParty string

// Repo is the public source repository: the only place it is defined in code.
const Repo = "https://github.com/p3374/GhostCam"

const header = `GhostCam — ` + Repo + `
Copyright (C) the GhostCam contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. It comes WITHOUT ANY WARRANTY. The complete source code is
available at the address above.

cloudflared is not part of GhostCam: it is downloaded at runtime from
Cloudflare's official releases and is licensed under the Apache License 2.0
(https://github.com/cloudflare/cloudflared/blob/master/LICENSE).

`

// Notices returns everything to display on the licenses page.
func Notices() string {
	return header + "==== GhostCam license (AGPL-3.0-or-later) ====\n\n" + license + "\n\n" + thirdParty
}
